import type { Labels } from '@arcsig-labs/editor/svelte';

/**
 * German for the strings a visitor meets in the playground. Anything left out keeps its English
 * default, which is how `labels` works: pass the ones you change.
 */
export const labelsDe: Partial<Labels> = {
	flowName: 'Name des Ablaufs',
	untitled: 'Unbenannter Ablauf',
	ready: 'Bereit',
	problemCount: '{count} Problem',
	problemsCount: '{count} Probleme',
	noteCount: '{count} Hinweis',
	notesCount: '{count} Hinweise',
	import: 'Importieren',
	export: 'Exportieren',
	testRun: 'Testlauf',
	stop: 'Stopp',
	searchSteps: 'Schritte suchen',
	noStepsMatch: 'Kein Schritt passt zu „{query}“.',
	addStepHint: 'Zum Hinzufügen klicken oder auf die Fläche ziehen',
	trigger: 'Auslöser',
	needsAttention: 'Braucht Aufmerksamkeit',
	looksGood: 'Sieht gut aus',
	flow: 'Ablauf',
	allGood: 'Alle Schritte sind verbunden und eingerichtet. Starte einen Testlauf und sieh zu.',
	settings: 'Einstellungen',
	inputTab: 'Eingabe',
	outputTab: 'Ausgabe',
	noRunData: 'Starte einen Testlauf, um zu sehen, was dieser Schritt bekommt und liefert.',
	runNow: 'Testlauf starten',
	runTitle: 'Testlauf',
	running: 'Läuft…',
	completed: 'Abgeschlossen',
	failed: 'Fehlgeschlagen',
	stopped: 'Gestoppt',
	simulated: 'Simuliert – Schritte ohne Testmodus laufen trotzdem',
	simulatedNothing: 'Simuliert – nichts wurde gesendet',
	simulatedOneRan: 'Simuliert – 1 Schritt hatte keinen Testmodus und lief wirklich',
	simulatedRan: 'Simuliert – {count} Schritte hatten keinen Testmodus und liefen wirklich',
	dataFromSteps: 'Daten aus früheren Schritten',
	dragToMap: 'Zieh einen Wert auf ein Feld oder tippe {{ in ein Feld, um einen auszuwählen.',
	notRunYet: 'Noch nicht gelaufen',
	preview: 'Vorschau',
	logs: 'Protokoll',
	undo: 'Rückgängig',
	redo: 'Wiederholen',
	addNote: 'Notiz',
	notePlaceholder: 'Notiz schreiben…',
	duplicate: 'Duplizieren',
	disable: 'Deaktivieren',
	enable: 'Aktivieren',
	delete: 'Löschen',
	insertStep: 'Schritt einfügen',
	pickToInsert: 'Hier einen Schritt einfügen',
	pickToConnect: 'Verbundenen Schritt hinzufügen',
	addStep: 'Schritt hinzufügen',
	steps: 'Schritte',
	more: 'Mehr',
	moreActions: 'Weitere Aktionen',
	close: 'Schließen',
	done: 'Fertig'
};
